name: Deploy to PREVIEW
on: pull_request
jobs:
  build_and_preview:
    permissions:
      checks: 'write'
      pull-requests: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAMES_FARRELLY }}'
          projectId: james-farrelly